### ISSUE TITLE
[FEATURE] Add a delay to the window animation

### ISSUE THREAD

**Issue by BrunoG1987** [peterfajdiga/kwin4_effect_geometry_change#3]
### Summary

Add a customizable delay to trigger the window animation to wait for other effects to conclude.

### Behavior on my machine
[Screencast_20230621_182753.webm](https://github.com/peterfajdiga/kwin4_effect_geometry_change/assets/98669123/3e71a449-fbf9-4146-aeb9-a6e729c86173)

### A clear and concise description of what I want to happen
- Termination of the effect on window close.
- The window(s) left open starts to animate.

(First ever post on Github. Please have patience if I have done something wrong!)

**Comment by peterfajdiga** [comment]
Hi, thanks for the clear and concise report!

I agree that such a work-around would mitigate the visual artifact you demonstrate in the video. However, I don't want to implement it, because in my experience, chaining animations like this feels less responsive/snappy. I haven't seen this in other Kwin effects either. Additionally, I'd prefer to keep this effect as simple as is reasonable.

I would guess that the visual artifact you get is caused by the blur effect (see if disabling blur or transparency solves it). Perhaps a better work-around would be to somehow disable blur while the close animation is playing.

**Comment by BrunoG1987** [comment]
Thank you for your point of view!
